name: smart_investment
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.  Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  # News_Bottom Page dependencies
  bubble_bottom_bar: ^1.2.0
  flutter_svg:
  rename: ^1.2.0

  # ==> FLUTTER FIREBASE
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  firebase_storage: any
  firebase_analytics: any
  flutter_signin_button: ^1.1.0
  flutter_facebook_login: ^3.0.0
  flutter_login_facebook: ^0.4.2+3
  flutter_facebook_auth: ^1.0.2+2
  provider: ^4.3.2+3
  mockito: ^4.1.3
  url_launcher: ^5.7.10
  newsapi: ^1.0.9
  test: ^1.15.7
  firebase_storage_mocks: ^0.2.1
  cloud_firestore_mocks: ^0.5.2+1
  firebase_database: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/background.png
