name: SmartInvestment
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.  Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #MySql database package
  mysql1: ^0.17.1
  # News_Bottom Page dependencies
  bubble_bottom_bar: ^1.2.0
  flutter_svg:
  rename: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/background.png
